name: screenshot_package_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Take Screenshot
  screenshot: ^2.3.0

  # Save Screenshot
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1

  # Save and Share Screenshot
  share_plus: ^8.0.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/